model:

  # name for saving
  prefix: cnn

  # activation function
  activation: relu

  in_channels: 2
  out_channels: 1

  # kernel size of first convolutional layer
  init_ksize: 2

  # pooling size for adaptive pooling at the end
  pool_size: [5, 5]

  K: 2
  layers: [2, 2, 2]
