defaults:
  - hydra/job_logging: custom
  - models: mlp
  - datasets: uniform
  - figures
  - train

# log to wandb
wandb: False

# toy dataset flag
toy: False

# for loading pretrained models
pretrained_model: None

hydra:
  run:
    dir: ./
