MODEL:  # TODO: Fill this in
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    NUM_CLASSES: 44
    SCORE_THRESH_TEST: 0.7
INPUT:
  MASK_FORMAT: 'bitmask'
DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TRAIN: ("sailvos_train",)
  TEST: ("sailvos_test",)
SOLVER:
  IMS_PER_BATCH: 5
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (8000, 10000)
  MAX_ITER: 11000
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.1
