# basic hyperparams
batch_size: 1000
lr: 3e-4
epochs: 5
random_seed: 20200802

# if doing random sampling train i.e. no defined 'epoch'
iters: 10000

# loss function for regression
loss: huber

# for boundary checking
atol: 1e-2

# training modes
error_correct: False

tuning:
    eta: 0

checkpoint:

    # default -1 to indicate no checkpointing
    # make non zero integer to periodically save models
    start: -1
    interval: 1

    checkpoint_dir: saved_models/checkpoint_0

# softmax temperature
alpha: 1.0

# for logging
skip: 20

